version: '2.1'
orbs:
  aws-ecs: circleci/aws-ecs@2.0
jobs:
  run-task:
    docker:
      - image: 'cimg/node:9.9.0'
    steps:
      - aws-ecs/run-task:
          cluster: $ECS_PARAM_CLUSTER_NAME
          security-group-ids: $SECURITY_GROUP_IDS
          subnet-ids: '$SUBNET_ONE, $SUBNET_TWO'
          task-definition: $My_Task_Def
workflows:
  run-task:
    jobs:
      - run-task