version: '2.1'
orbs:
  aws-ecs: circleci/aws-ecs@2.0
jobs:
  run-task:
    docker:
      - image: cibuilds/aws:2.1.27
      - image: cimg/python:3.8
    steps:
      - aws-ecs/run-task:
          capacity-provider-strategy: >-
            capacityProvider=FARGATE,weight=1
            capacityProvider=FARGATE_SPOT,weight=1
          cluster: ecs-fargate
          count: 4
          launch-type: ''
          security-group-ids: $SECURITY_GROUP_IDS
          subnet-ids: '$SUBNET_ONE, $SUBNET_TWO'
          task-definition: fargate-webapp-task
          assign-public-ip : ENABLED         
workflows:
  run-task:
    jobs:
      - run-task
