version: '2.1'
orbs:
  aws-ecs: circleci/aws-ecs@2.0
deploy:
    docker:
      - image: cibuilds/aws:1.16.1  
jobs:
  run-task:
    docker:
      - image: cibuilds/aws:1.16.1  
      - image: 'cimg/python:3.9.1'
    steps:
      - aws-ecs/run-task:
          cluster: $ECS_PARAM_CLUSTER_NAME
          security-group-ids: $SECURITY_GROUP_IDS
          subnet-ids: '$SUBNET_ONE, $SUBNET_TWO'
          task-definition: $My_Task_Def
workflows:
  run-task:
    jobs:
      - run-task