version: '2.1'
orbs:
  aws-ecs: circleci/aws-ecs@2.0
jobs:
  run-task:
    docker:
      - image: 'cimg/python:3.9.1'
    steps:
      - aws-ecs/run-task:
          capacity-provider-strategy: >-
            capacityProvider=FARGATE,weight=1
            capacityProvider=FARGATE_SPOT,weight=1
          cluster: $CLUSTER_NAME
          launch-type: ''
          security-group-ids: $SECURITY_GROUP_IDS_FETCHED
          subnet-ids: '$SUBNET_ONE, $SUBNET_TWO'
          task-definition: $My_Task_Def
workflows:
  run-task:
    jobs:
      - run-task